// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PilamungaS_Taller.Data;

#nullable disable

namespace PilamungaS_Taller.Migrations
{
    [DbContext(typeof(PilamungaS_TallerContext))]
    [Migration("20250501001256_Migracionnueva")]
    partial class Migracionnueva
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PilamungaS_Taller.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PartidosEmpatados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosGanados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosPerdidos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Conocida como LDU Quito, es uno de los clubes más exitosos del país, con títulos nacionales e internacionales, incluyendo la Copa Libertadores.",
                            Logo = "/img/ldu.png",
                            Nombre = "Liga de quito",
                            PartidosEmpatados = 2,
                            PartidosGanados = 3,
                            PartidosPerdidos = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Uno de los clubes más populares y exitosos de Ecuador, con múltiples títulos nacionales e internacionales. Su hinchada, conocida como los amarillos, es muy apasionada.",
                            Logo = "/img/bsc.png",
                            Nombre = "Barcelona",
                            PartidosEmpatados = 0,
                            PartidosGanados = 5,
                            PartidosPerdidos = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Este equipo, anteriormente conocido como Cuniburo, ascendió por primera vez a la Serie A en 2025, buscando dejar su huella en la máxima categoría.",
                            Logo = "/img/cnb.png",
                            Nombre = "Cuniburo/Vinotinto",
                            PartidosEmpatados = 3,
                            PartidosGanados = 4,
                            PartidosPerdidos = 1
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Representando a la capital, la Chatoleí ha sido un equipo que ha luchado por mantenerse en la Serie A y busca consolidarse en la élite del fútbol ecuatoriano.",
                            Logo = "/img/uct.png",
                            Nombre = "U.Catolica",
                            PartidosEmpatados = 3,
                            PartidosGanados = 3,
                            PartidosPerdidos = 1
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Ubicado en Sangolquí, Independiente ha ganado reconocimiento por su sólida formación de jugadores y buenas actuaciones en competiciones internacionales.",
                            Logo = "/img/inv.png",
                            Nombre = "Independiente",
                            PartidosEmpatados = 3,
                            PartidosGanados = 3,
                            PartidosPerdidos = 1
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Representante de Loja, Libertad ha sido un equipo que ha luchado por mantenerse en la Serie A y busca consolidarse en la élite del fútbol ecuatoriano.​",
                            Logo = "/img/lbt.jpeg",
                            Nombre = "Libertad",
                            PartidosEmpatados = 2,
                            PartidosGanados = 3,
                            PartidosPerdidos = 2
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Fundado en 1971, el Expreso Austral ha sido un equipo competitivo en la Serie A, con una hinchada fiel y estadios con gran ambiente.",
                            Logo = "/img/dcu.png",
                            Nombre = "Dep.Cuenca",
                            PartidosEmpatados = 1,
                            PartidosGanados = 3,
                            PartidosPerdidos = 4
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Representante de Machala, Orense ha sido un equipo que ha luchado por mantenerse en la Serie A y busca consolidarse en la élite del fútbol ecuatoriano.",
                            Logo = "/img/orn.png",
                            Nombre = "Orense",
                            PartidosEmpatados = 1,
                            PartidosGanados = 3,
                            PartidosPerdidos = 3
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Equipo con sede en Ambato, Mushuc Runa ha sido conocido por su lucha y esfuerzo en la Serie A, buscando siempre mejorar su rendimiento.",
                            Logo = "/img/msr.png",
                            Nombre = "MushucRuna",
                            PartidosEmpatados = 3,
                            PartidosGanados = 2,
                            PartidosPerdidos = 2
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Fundado en 1945, Aucas es un club con sede en el sur de Quito. Ha tenido participaciones destacadas en la Serie A y busca consolidarse entre los mejores del país.",
                            Logo = "/img/auc.png",
                            Nombre = "Aucas",
                            PartidosEmpatados = 3,
                            PartidosGanados = 2,
                            PartidosPerdidos = 2
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "Fundado en 1948, Macará es un equipo con sede en Ambato que ha tenido participaciones destacadas en la Serie A y busca volver a sus épocas de gloria.",
                            Logo = "/img/mca.png",
                            Nombre = "Macara",
                            PartidosEmpatados = 3,
                            PartidosGanados = 2,
                            PartidosPerdidos = 3
                        },
                        new
                        {
                            Id = 12,
                            Descripcion = "Tras su ascenso, Manta regresa a la Serie A con el objetivo de mantenerse y competir al más alto nivel.",
                            Logo = "/img/mnt.png",
                            Nombre = "Manta",
                            PartidosEmpatados = 3,
                            PartidosGanados = 2,
                            PartidosPerdidos = 3
                        },
                        new
                        {
                            Id = 13,
                            Descripcion = "Fundado en 2008, El Rodillo del Tungurahua ha sido un equipo que ha luchado por mantenerse en la Serie A y busca consolidarse en la élite del fútbol ecuatoriano.",
                            Logo = "/img/tuv.png",
                            Nombre = "TecnicoUniversitario",
                            PartidosEmpatados = 3,
                            PartidosGanados = 1,
                            PartidosPerdidos = 4
                        },
                        new
                        {
                            Id = 14,
                            Descripcion = "Fundado en 1929, Emelec es uno de los clubes más laureados de Ecuador, con una gran hinchada y rivalidad histórica con Barcelona SC.​",
                            Logo = "/img/emc.png",
                            Nombre = "Emelec",
                            PartidosEmpatados = 3,
                            PartidosGanados = 1,
                            PartidosPerdidos = 3
                        },
                        new
                        {
                            Id = 15,
                            Descripcion = "Representante de la ciudad de Manta, Delfín ha sido protagonista en los últimos años, logrando títulos y destacadas actuaciones en competiciones internacionales.",
                            Logo = "/img/del.png",
                            Nombre = "Delfin",
                            PartidosEmpatados = 3,
                            PartidosGanados = 1,
                            PartidosPerdidos = 4
                        },
                        new
                        {
                            Id = 16,
                            Descripcion = "Con sede en Quito, El Nacional ha sido históricamente uno de los clubes más importantes del país, con una rica historia y múltiples títulos.",
                            Logo = "/img/nac.png",
                            Nombre = "Nacional",
                            PartidosEmpatados = 2,
                            PartidosGanados = 1,
                            PartidosPerdidos = 4
                        });
                });

            modelBuilder.Entity("PilamungaS_Taller.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsistenciasTotales")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("Goles")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroCamiseta")
                        .HasColumnType("int");

                    b.Property<float>("Sueldo")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("PilamungaS_Taller.Models.Jugador", b =>
                {
                    b.HasOne("PilamungaS_Taller.Models.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("PilamungaS_Taller.Models.Equipo", b =>
                {
                    b.Navigation("Jugadores");
                });
#pragma warning restore 612, 618
        }
    }
}
